 USE astronomija;

SET FOREIGN_KEY_CHECKS = 0; 

TRUNCATE TABLE INVENTAR_RESURSA;
TRUNCATE TABLE ISTRAZIVAC;
TRUNCATE TABLE NEBESKI_OBJEKAT;
TRUNCATE TABLE TEORIJA;
TRUNCATE TABLE TIP_ALATA;
TRUNCATE TABLE RESURS;
TRUNCATE TABLE OPSERVATORIJA;

SET FOREIGN_KEY_CHECKS = 1;