 USE astronomija;

SET FOREIGN_KEY_CHECKS = 0; 

TRUNCATE TABLE UTROSENI_RESURSI_SESIJE;
TRUNCATE TABLE ISKORISCENI_ALATI_SESIJE;
TRUNCATE TABLE SESIJA;
TRUNCATE TABLE TIM_IZVODJACA;
TRUNCATE TABLE IZVODJENJE;
TRUNCATE TABLE POTREBAN_ALAT_ZA_EKSPERIMENT;
TRUNCATE TABLE POTREBAN_RESURS_ZA_EKSPERIMENT;
TRUNCATE TABLE CILJ_POSMATRANJA;
TRUNCATE TABLE DIZAJNER_EKSPERIMENTA;
TRUNCATE TABLE EKSPERIMENT;
TRUNCATE TABLE ALAT;
TRUNCATE TABLE INVENTAR_RESURSA;
TRUNCATE TABLE ISTRAZIVAC;
TRUNCATE TABLE NEBESKI_OBJEKAT;
TRUNCATE TABLE TEORIJA;
TRUNCATE TABLE TIP_ALATA;
TRUNCATE TABLE RESURS;
TRUNCATE TABLE OPSERVATORIJA;
TRUNCATE TABLE KORISNIK;

SET FOREIGN_KEY_CHECKS = 1;